name: trees_to_seas
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xarray
  - netcdf4
  - geopandas
  - shapely
  - pyproj
  - matplotlib
  - pyyaml
  - tqdm
  - statsmodels
  - jupyter
  - ipykernel
  - ipywidgets
  - pytest
  - pytest-cov
  - ruff
  - pre-commit
  - pip
  - pip:
      - -e .
